# **Theoretical Questions:**

**Q1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it  enhance Python's capabilities for numerical operations?**

**Ans1.** NumPy (Numerical Python) is a powerful library in Python that focuses on numerical computing and is widely used in scientific computing and data analysis. Here's why it's so important:

### **Purpose of NumPy**
- **Efficient Numerical Computations**: NumPy provides a high-performance multidimensional array object called `ndarray` that allows fast and efficient numerical calculations.
- **Scientific Data Handling**: It's designed for handling large datasets and performing complex mathematical operations on them easily.

### **Advantages of NumPy**
1. **Speed**: NumPy is much faster than regular Python lists because it uses optimized C code for array operations.
2. **Memory Efficiency**: It uses less memory compared to Python lists since it stores data in a compact and contiguous memory format.
3. **Broad Functionality**: It includes built-in functions for mathematical operations like linear algebra, Fourier transforms, and random number generation.
4. **Convenient Array Operations**: NumPy supports element-wise operations, which means you can perform arithmetic directly on entire arrays without using loops.
5. **Interoperability**: NumPy integrates well with other libraries like Pandas, Matplotlib, and SciPy, enhancing its usage in data science and machine learning workflows.

### **How NumPy Enhances Python’s Capabilities**
- **Vectorized Operations**: Instead of writing loops to perform operations on each element, NumPy allows you to perform vectorized operations, making code cleaner and faster.
- **Multi-Dimensional Arrays**: NumPy introduces arrays that can have more than one dimension (like matrices), which Python lists don't natively support.
- **Broadcasting**: This feature allows you to perform operations on arrays of different shapes, simplifying many tasks without writing complex code.

In summary, NumPy transforms Python into a more efficient tool for handling large datasets and performing numerical computations, making it indispensable for scientific computing and data analysis.

**Q2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the  other?**

**Ans2.**
### **Comparing `np.mean()` and `np.average()` in NumPy**

Both `np.mean()` and `np.average()` are used to calculate the average of an array, but they have some key differences:

---

### **1. `np.mean()`**
- **Definition**: Calculates the arithmetic mean (simple average) of the elements in an array.
- **Syntax**: `np.mean(array, axis=None)`
- **Weights**: It does **not** support weights; it treats all elements equally.
- **Use Case**: Use `np.mean()` when you want a straightforward average without considering the importance or weight of individual elements.

#### **Example**:

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr)
print(mean_value)  # Output: 3.0

### **2. `np.average()`**
- **Definition**: Calculates a weighted average, where you can specify the importance of each element.
- **Syntax**: `np.average(array, weights=None, axis=None)`
- **Weights**: Supports weights, allowing some elements to contribute more to the final average than others.
- **Use Case**: Use `np.average()` when you need to calculate an average that gives different importance (weights) to different elements.

#### **Example**:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])  # Higher weight for higher values
weighted_average = np.average(arr, weights=weights)
print(weighted_average)  # Output: 3.666...



### **Key Differences**
| Feature              | `np.mean()`                      | `np.average()`                    |
|----------------------|-----------------------------------|-----------------------------------|
| **Weights**           | Not supported                     | Supported                          |
| **Use Case**          | Simple arithmetic mean             | Weighted average                    |
| **Performance**       | Slightly faster (no weights)       | Slightly slower (with weights)      |

---

### **When to Use Which?**
- **Use `np.mean()`**: When all elements should contribute equally to the average, like calculating the average temperature over a week.
- **Use `np.average()`**: When different elements have different levels of importance, like calculating a student’s weighted grade based on different subjects' importance.


**Q3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D  arrays.**

**Ans3.**
### **Reversing a NumPy Array Along Different Axes**

Reversing a NumPy array means flipping the order of its elements. NumPy provides several methods to reverse arrays, depending on the dimensionality and the axis you want to reverse.

---

### **1. Reversing a 1D Array**

#### **Method: Slicing (`[::-1]`)**
The easiest way to reverse a 1D array is using slicing with a step of `-1`.

#### **Example**:

In [ ]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])
reversed_1d = arr_1d[::-1]
print(reversed_1d)  # Output: [5 4 3 2 1]

### **2. Reversing a 2D Array**

#### **Method 1: Reverse Entire Array**
You can reverse the entire 2D array by applying slicing.

#### **Example**:

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_2d = arr_2d[::-1, ::-1]
print(reversed_2d)
# Output:
# [[9 8 7]
#  [6 5 4]
#  [3 2 1]]

#### **Method 2: Reverse Along Rows (Axis 0)**
To reverse only the rows (flip vertically):

In [ ]:
reversed_rows = arr_2d[::-1, :]
print(reversed_rows)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]

#### **Method 3: Reverse Along Columns (Axis 1)**
To reverse only the columns (flip horizontally):

In [ ]:
reversed_cols = arr_2d[:, ::-1]
print(reversed_cols)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]



### **Summary of Methods**
| Reversal Type       | Code                              | Explanation                                     |
|---------------------|-----------------------------------|-------------------------------------------------|
| **1D Reversal**      | `arr[::-1]`                       | Reverses the entire 1D array                    |
| **2D Entire Reversal**| `arr[::-1, ::-1]`                 | Reverses both rows and columns                  |
| **Rows Reversal**    | `arr[::-1, :]`                    | Reverses only the rows                          |
| **Columns Reversal** | `arr[:, ::-1]`                    | Reverses only the columns                       |

By using these simple slicing techniques, you can easily manipulate and reverse arrays in any direction! 😊

**Q4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types  in memory management and performance.**

**Ans4.**
### **Determining the Data Type of Elements in a NumPy Array**

In NumPy, you can determine the data type of elements in an array using the `.dtype` attribute.

#### **Example**:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)  # Output: int64 (or int32 depending on the system)

float_arr = np.array([1.5, 2.5, 3.5])
print(float_arr.dtype)  # Output: float64

### **Importance of Data Types in Memory Management and Performance**

#### 1. **Memory Efficiency**
- Different data types require different amounts of memory. For example:
  - `int8` (8 bits) requires **1 byte** per element.
  - `int32` (32 bits) requires **4 bytes** per element.
  - `float64` (64 bits) requires **8 bytes** per element.
- By selecting an appropriate data type, you can save memory. For large datasets, this can be crucial.

#### **Example**:

In [ ]:
large_arr = np.array([1, 2, 3], dtype=np.int8)  # Uses less memory
print(large_arr.nbytes)  # Output: 3 bytes (1 byte per element)

large_float_arr = np.array([1.0, 2.0, 3.0], dtype=np.float64)
print(large_float_arr.nbytes)  # Output: 24 bytes (8 bytes per element)

#### 2. **Performance Optimization**
- Operations on arrays with smaller or simpler data types are faster because less data needs to be processed.
- For example, arithmetic operations on `int32` arrays are faster than on `float64` arrays due to smaller memory size and simpler computations.

#### **Example**:

In [ ]:
int_arr = np.array([1, 2, 3], dtype=np.int32)
float_arr = np.array([1.0, 2.0, 3.0], dtype=np.float64)

# Arithmetic operations
int_sum = int_arr + int_arr  # Faster
float_sum = float_arr + float_arr  # Slightly slower



### **Why Data Types Matter**
1. **Memory Management**: Choosing the right data type minimizes memory usage, which is critical for large datasets.
2. **Speed**: Smaller data types lead to faster computations, improving overall program performance.
3. **Precision**: Data types like `float64` provide more precision, useful for scientific calculations, while `int` types are better for counting or discrete data.

In summary, understanding and using appropriate data types in NumPy helps balance memory usage, speed, and precision, making your programs more efficient and effective.

**Q5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?**

**Ans5.**
### **Definition of `ndarray` in NumPy**

An **`ndarray`** (N-dimensional array) is the core data structure provided by NumPy for handling large, multi-dimensional arrays of homogeneous data. It allows efficient storage and manipulation of numerical data in a structured way.

---

### **Key Features of `ndarray`**

1. **Multidimensional**: Can handle arrays with any number of dimensions (1D, 2D, 3D, etc.).
   - Example: 1D vector, 2D matrix, 3D tensor.
   
2. **Homogeneous Data**: All elements in an `ndarray` must be of the same data type (e.g., `int`, `float`).
   
3. **Efficient Memory Usage**: `ndarray` stores data in contiguous blocks of memory, making it more memory-efficient than Python lists.
   
4. **Vectorized Operations**: Supports element-wise operations without the need for loops, enhancing performance.
   - Example: `arr * 2` multiplies every element by 2.
   
5. **Shape and Size Attributes**: Provides useful attributes like `.shape` (dimensions of the array) and `.size` (total number of elements).
   - Example:

In [ ]:
     arr = np.array([[1, 2], [3, 4]])
     print(arr.shape)  # Output: (2, 2)
     print(arr.size)   # Output: 4

6. **Broadcasting**: Supports operations on arrays of different shapes without explicitly reshaping them.



### **Differences Between `ndarray` and Python Lists**

| Feature               | `ndarray` (NumPy)                           | Python List                          |
|-----------------------|---------------------------------------------|--------------------------------------|
| **Data Type**          | Homogeneous (all elements must be the same)  | Heterogeneous (can hold mixed types) |
| **Performance**        | Faster due to optimized C-based operations   | Slower, especially for large datasets|
| **Memory Usage**       | More memory-efficient                        | Less efficient (due to pointers)     |
| **Operations**         | Supports vectorized operations (e.g., `arr * 2`) | Requires explicit loops for operations |
| **Dimensionality**     | Supports multidimensional arrays (e.g., 2D, 3D) | Lists are typically 1D; nesting is needed for multi-dimensions |
| **Functions**          | Has built-in mathematical functions (e.g., `np.sum()`) | No direct support for such operations |

---

### **Example Comparison**

#### **NumPy `ndarray` Example**:

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr * 2)  # Output: [2 4 6 8]

#### **Python List Example**:

In [ ]:
lst = [1, 2, 3, 4]
print([x * 2 for x in lst])  # Output: [2, 4, 6, 8]



### **Summary**

- `ndarray` is designed for efficient numerical computations and works much faster than Python lists, especially with large datasets.
- While Python lists are flexible and easy to use, `ndarray` offers better performance, memory efficiency, and built-in mathematical capabilities, making it ideal for scientific computing and data analysis.

**Q6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.**




**Ans6.**
### **Performance Benefits of NumPy Arrays Over Python Lists for Large-Scale Numerical Operations**

NumPy arrays (`ndarray`) are significantly faster and more efficient than Python lists when dealing with large-scale numerical data. Let’s break down why:

---

### **1. Speed and Efficiency**

#### **Reason: Vectorized Operations**
- **NumPy Arrays**: Operations are executed using optimized C/C++ code, allowing element-wise operations without loops.
- **Python Lists**: Operations require explicit loops, making them slower due to the interpreted nature of Python.

#### **Example: Adding Two Arrays/Lists**

In [ ]:
import numpy as np
import time

# NumPy Array
arr = np.arange(1_000_000)
start = time.time()
arr_sum = arr + arr  # Vectorized operation
end = time.time()
print("NumPy time:", end - start)

# Python List
lst = list(range(1_000_000))
start = time.time()
lst_sum = [x + x for x in lst]  # Loop-based operation
end = time.time()
print("List time:", end - start)

**Result**: NumPy is **much faster** because it avoids the overhead of Python loops.

---

### **2. Memory Efficiency**

#### **Reason: Compact Storage**
- **NumPy Arrays**: Store elements in contiguous memory blocks, reducing memory overhead.
- **Python Lists**: Store elements as objects with pointers, which increases memory usage.

#### **Example: Memory Usage Comparison**

In [ ]:
import sys

# NumPy Array
arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)
print("NumPy memory:", arr.nbytes)  # Output: 20 bytes

# Python List
lst = [1, 2, 3, 4, 5]
print("List memory:", sys.getsizeof(lst))  # Output: Larger than NumPy

**Result**: NumPy uses significantly **less memory** than Python lists.

---

### **3. Built-in Mathematical Functions**

- **NumPy Arrays**: Provide a wide range of optimized mathematical functions (e.g., `np.sum()`, `np.mean()`).
- **Python Lists**: Require manual loops or external functions like `sum()`, which are less efficient.

#### **Example: Summing Elements**

In [ ]:
# NumPy Array
arr = np.arange(1_000_000)
print("NumPy sum:", np.sum(arr))  # Fast and efficient

# Python List
lst = list(range(1_000_000))
print("List sum:", sum(lst))  # Slower than NumPy


### **4. Multi-Dimensional Support**
- **NumPy Arrays**: Support multidimensional arrays (e.g., 2D matrices, 3D tensors) natively, making them ideal for scientific computations.
- **Python Lists**: Require nested lists for multi-dimensional data, leading to more complex code and slower performance.

---

### **5. Broadcasting**

NumPy supports **broadcasting**, which allows operations between arrays of different shapes without explicit looping or reshaping. Python lists require manual handling of shapes.

#### **Example: Broadcasting**

In [ ]:
arr = np.array([1, 2, 3])
matrix = np.array([[10], [20], [30]])
print(arr + matrix)
# Output:
# [[11 12 13]
#  [21 22 23]
#  [31 32 33]]



### **Conclusion**

- **NumPy arrays** are faster, more memory-efficient, and easier to use for large-scale numerical operations due to their optimized C-based implementation, vectorized operations, and broadcasting capabilities.
- **Python lists**, while more flexible for general-purpose tasks, are slower and less efficient for numerical computations, making NumPy a clear choice for data analysis, scientific computing, and machine learning tasks. 😊

**Q7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.**

**Ans7.**
### **Comparison of `vstack()` and `hstack()` Functions in NumPy**

Both `vstack()` and `hstack()` are used to combine arrays, but they do so in different ways:

---

### **1. `vstack()` – Vertical Stacking**
- **Definition**: Stacks arrays **vertically** (along rows).
- **Behavior**: Combines arrays by placing them one on top of the other.
- **Shape Requirement**: Arrays must have the **same number of columns** (i.e., same width).

#### **Example**:

In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Vertical stacking
result_vstack = np.vstack((arr1, arr2))
print(result_vstack)

Output:
[[1 2]
[3 4]
[5 6]]

### **2. `hstack()` – Horizontal Stacking**
- **Definition**: Stacks arrays **horizontally** (along columns).
- **Behavior**: Combines arrays by placing them side by side.
- **Shape Requirement**: Arrays must have the **same number of rows** (i.e., same height).

#### **Example**:

In [ ]:
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5], [6]])

# Horizontal stacking
result_hstack = np.hstack((arr3, arr4))
print(result_hstack)

Output:

[[1 2 5]
 [3 4 6]]



### **Key Differences Between `vstack()` and `hstack()`**

| Feature            | `vstack()`                           | `hstack()`                            |
|--------------------|--------------------------------------|---------------------------------------|
| **Stacking Direction** | Vertical (row-wise)                  | Horizontal (column-wise)               |
| **Shape Requirement** | Same number of columns               | Same number of rows                    |
| **Resulting Shape**  | Rows increase, columns stay the same  | Columns increase, rows stay the same   |

---

### **Example Using Both Functions**

In [ ]:
arr_a = np.array([1, 2])
arr_b = np.array([3, 4])

# Reshaping for demonstration
arr_a_reshaped = arr_a.reshape(1, -1)  # [[1, 2]]
arr_b_reshaped = arr_b.reshape(1, -1)  # [[3, 4]]

# Vertical Stack
print("Vertical Stack:")
print(np.vstack((arr_a_reshaped, arr_b_reshaped)))

# Horizontal Stack
print("Horizontal Stack:")
print(np.hstack((arr_a_reshaped, arr_b_reshaped)))

Output:

Vertical Stack:
[[1 2]
 [3 4]]

Horizontal Stack:
[[1 2 3 4]]


### **Conclusion**
- Use **`vstack()`** when you need to stack arrays vertically (one below the other).
- Use **`hstack()`** when you need to stack arrays horizontally (side by side).
These functions are particularly useful for combining datasets in different shapes while maintaining efficient code!

**Q8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions**

**Ans8.**
### **Differences Between `fliplr()` and `flipud()` in NumPy**

Both `fliplr()` and `flipud()` are used to reverse the order of elements in a 2D (or higher-dimensional) NumPy array, but they operate along different axes:

---

### **1. `fliplr()` – Flip Left to Right**
- **Definition**: Flips the array **horizontally**, reversing the order of columns.
- **Effect**: The first column becomes the last, the second becomes the second-to-last, and so on.
- **Supported Arrays**: Requires at least a **2D array** (won’t work on 1D arrays).

#### **Example**:

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

flipped_lr = np.fliplr(arr)
print(flipped_lr)

Output:

[[3 2 1]
 [6 5 4]
 [9 8 7]]

### **2. `flipud()` – Flip Up to Down**
- **Definition**: Flips the array **vertically**, reversing the order of rows.
- **Effect**: The first row becomes the last, the second row becomes the second-to-last, and so on.
- **Supported Arrays**: Works on **all arrays**, including 1D arrays.

#### **Example**:

In [ ]:
flipped_ud = np.flipud(arr)
print(flipped_ud)
```
**Output**:
```
[[7 8 9]
 [4 5 6]
 [1 2 3]]

### **Key Differences Between `fliplr()` and `flipud()`**

| Feature                | `fliplr()` (Left to Right)           | `flipud()` (Up to Down)              |
|------------------------|--------------------------------------|--------------------------------------|
| **Axis of Operation**   | Horizontal (along columns)           | Vertical (along rows)                |
| **Effect on 2D Arrays** | Reverses the column order             | Reverses the row order               |
| **Works on 1D Arrays**  | No (throws an error)                 | Yes (reverses the entire array)      |

---

### **Example with 1D Array for `flipud()`**

In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5])

flipped_1d = np.flipud(arr_1d)
print(flipped_1d)  # Output: [5 4 3 2 1]
```
**Note**: `fliplr()` would not work here because it requires at least a 2D array.



### **Effect on Higher-Dimensional Arrays**

- **`fliplr()`**: Reverses columns in each 2D slice of a higher-dimensional array.
- **`flipud()`**: Reverses rows in each 2D slice of a higher-dimensional array.

#### **Example with 3D Array**:

In [ ]:
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])

print("Original 3D array:")
print(arr_3d)

print("\nfliplr:")
print(np.fliplr(arr_3d))

print("\nflipud:")
print(np.flipud(arr_3d))


### **Conclusion**
- **`fliplr()`** is useful when you need to reverse columns (horizontal flipping), while **`flipud()`** is used for reversing rows (vertical flipping).
- Knowing which method to use depends on whether you want to flip the array along its horizontal or vertical axis!

**Q9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?**

**Ans9.**
### **Functionality of `array_split()` in NumPy**

The `array_split()` method in NumPy is used to split an array into multiple sub-arrays. It is more flexible than `split()` because it can handle **uneven splits**, distributing the remaining elements across sub-arrays.

---

### **Syntax**:

In [ ]:
np.array_split(array, indices_or_sections, axis=0)

- **`array`**: The array to be split.
- **`indices_or_sections`**: Specifies how many parts to split the array into.
  - If it's an integer, it splits the array into that many parts.
- **`axis`** (optional): The axis along which to split. Default is `0` (rows).

---

### **Key Features**:
1. **Handles Uneven Splits**: If the array cannot be divided evenly, `array_split()` creates sub-arrays with different sizes.
2. **Supports Multi-Dimensional Arrays**: Can split along different axes.

---

### **Examples**

#### **1. Even Split**

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.array_split(arr, 3)
print(split_arr)  # Output: [array([1, 2]), array([3, 4]), array([5, 6])]




**Explanation**: The array is evenly split into three parts, each containing two elements.
#### **2. Uneven Split**

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
split_arr = np.array_split(arr, 3)
print(split_arr)
# Output: [array([1, 2, 3]), array([4, 5]), array([6, 7])]

**Explanation**: The array has 7 elements, which can't be evenly split into 3 parts. The first sub-array gets 3 elements, while the rest get 2 elements each.

#### **3. Splitting a 2D Array Along Rows (Axis 0)**

In [ ]:
arr_2d = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
split_2d = np.array_split(arr_2d, 3, axis=0)
print(split_2d)
# Output:
# [array([[1, 2], [3, 4]]),
#  array([[5, 6]]),
#  array([[7, 8]])]

#### **4. Splitting a 2D Array Along Columns (Axis 1)**

In [ ]:
split_2d_col = np.array_split(arr_2d, 3, axis=1)
print(split_2d_col)
# Output:
# [array([[1],
#         [3],
#         [5],
#         [7]]),
#  array([[2],
#         [4],
#         [6],
#         [8]]),
#  array([], shape=(4, 0), dtype=int64)]


**Explanation**: The array is split into 3 uneven column sub-arrays, with one empty array when the columns can't be evenly split.

---

### **Difference Between `split()` and `array_split()`**
- **`split()`**: Raises an error if the array can't be split evenly.
- **`array_split()`**: Handles uneven splits gracefully by distributing extra elements.

---

### **Conclusion**
`array_split()` is a flexible and powerful method for splitting arrays, especially when dealing with uneven splits. It's particularly useful for dividing datasets into batches or chunks for machine learning, data processing, or parallel computing tasks.

**Q10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?**

**Ans10.**
### **Concepts of Vectorization and Broadcasting in NumPy**

Both **vectorization** and **broadcasting** are powerful concepts in NumPy that enable efficient array operations. They optimize performance by avoiding explicit loops and reducing computational complexity.

---

### **1. Vectorization in NumPy**

**Vectorization** refers to the process of converting operations that would typically require loops into **element-wise operations** that can be performed directly on NumPy arrays.

- **Goal**: Instead of using a Python `for` loop to iterate over each element of an array, NumPy performs the operation on the entire array in one step, leveraging optimized low-level C implementations.
- **Benefit**: This approach is much faster because NumPy uses compiled code that avoids Python's overhead of interpreting loops.

#### **Example of Vectorized Operation:**

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

# Without vectorization (using loops):
result_loop = []
for x in arr:
    result_loop.append(x * 2)

# With vectorization:
result_vec = arr * 2

print(result_vec)  # Output: [2 4 6 8]

**Explanation**: The vectorized operation `arr * 2` applies the multiplication to all elements of `arr` without explicit looping.

---

### **2. Broadcasting in NumPy**

**Broadcasting** is a set of rules that allow NumPy to perform operations on arrays of different shapes in a way that they are made compatible (by "stretching" or "broadcasting" the smaller array to the size of the larger one).

- **Goal**: Avoid the need for manually reshaping arrays to perform operations, reducing memory usage and code complexity.
- **Benefit**: Broadcasting allows NumPy to perform operations on arrays with different shapes efficiently without explicitly replicating data.

#### **Broadcasting Rules:**
1. **If arrays have the same shape**, the operation is straightforward (element-wise operation).
2. **If the arrays have different shapes**, NumPy compares their shapes starting from the trailing dimensions. If the dimensions are compatible (either the sizes are the same or one of them is 1), broadcasting can occur.
3. **If a dimension size is 1**, it gets "stretched" or replicated to match the larger dimension.

---

### **Example of Broadcasting:**

#### **1. Broadcasting with Different Shapes**

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([[10], [20], [30]])

result = arr1 + arr2
print(result)

Output:

[[11 12 13]
 [22 23 24]
 [33 34 35]]

**Explanation**:
- `arr1` is of shape `(3,)`, and `arr2` is of shape `(3,1)`.
- NumPy broadcasts `arr1` across the second axis of `arr2` (turning `arr1` into a `(3,3)` array by repeating its elements), and the addition happens element-wise.

#### **2. Broadcasting with Scalar**

In [ ]:
arr = np.array([1, 2, 3])

# Broadcasting a scalar across the array
result = arr + 10
print(result)  # Output: [11 12 13]


**Explanation**: The scalar `10` is broadcasted to each element of the array, adding 10 to each element.

---

### **How Vectorization and Broadcasting Contribute to Efficient Array Operations**

1. **Performance Optimization**:
   - **Vectorization** eliminates the need for explicit loops, allowing NumPy to perform operations on entire arrays in a single step, which is much faster due to the optimized C code.
   - **Broadcasting** avoids the need to manually reshape arrays or replicate data, reducing both memory usage and the complexity of the code.

2. **Memory Efficiency**:
   - With **broadcasting**, smaller arrays don't need to be explicitly replicated across memory to match the shape of larger arrays. Instead, NumPy works with the original shapes and performs the necessary adjustments on the fly.
   - **Vectorization** eliminates unnecessary memory usage by performing operations on the entire array in one go rather than element-by-element.

3. **Cleaner Code**:
   - **Vectorized** code is concise and easier to read, avoiding verbose looping constructs.
   - **Broadcasting** simplifies operations between arrays of different shapes without manually reshaping arrays, making code cleaner and more intuitive.

---

### **Summary**
- **Vectorization** allows operations to be applied to entire arrays without loops, boosting performance by leveraging low-level C operations.
- **Broadcasting** enables operations on arrays of different shapes by stretching smaller arrays, saving memory and improving performance.

Together, **vectorization** and **broadcasting** make NumPy a powerful tool for efficient numerical computation, enabling operations on large datasets with minimal overhead.

# **Practical Questions:**

**Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.**

**Ans1.** Here's how you can solve this step by step:

1. Create a 3x3 array with random integers between 1 and 100 using `np.random.randint`.
2. Interchange the rows and columns using the `.T` attribute, which transposes the array.

Here’s the code:

In [ ]:
import numpy as np

# Step 1: Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(array)

# Step 2: Interchange rows and columns (transpose)
transposed_array = array.T
print("\nTransposed Array:")
print(transposed_array)


When you run this, you’ll see the original and transposed arrays.

**Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.**

**Ans2.** This is a fun one! Here's the step-by-step guide:

1. Create a 1D NumPy array with 10 elements using `np.arange` or any method you like.
2. Reshape it into a 2x5 array using the `.reshape()` method.
3. Reshape the 2x5 array into a 5x2 array.

Here’s the code:

In [ ]:
import numpy as np

# Step 1: Create a 1D array with 10 elements
array_1d = np.arange(10)
print("1D Array:")
print(array_1d)

# Step 2: Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped into 2x5 Array:")
print(array_2x5)

# Step 3: Reshape it into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)
print("\nReshaped into 5x2 Array:")
print(array_5x2)


### Key Points:
- The `reshape()` method doesn’t change the data; it just reorganizes the structure.
- The product of dimensions (e.g., \(2 \times 5\) or \(5 \times 2\)) must match the total number of elements in the array.



**Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**

**Ans3.** Adding a border of zeros around a NumPy array is straightforward with the `np.pad` function. Here’s how to do it step by step:

1. Create a 4x4 array with random float values using `np.random.rand`.
2. Use `np.pad` to add a border of zeros around the array.

Here’s the code:

In [ ]:
import numpy as np

# Step 1: Create a 4x4 array with random float values
array = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(array)

# Step 2: Add a border of zeros around the array
array_with_border = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print("\nArray with Border (6x6):")
print(array_with_border)


### Key Points:
- The `pad_width=1` adds a 1-cell-wide border.
- `mode='constant'` ensures the added border consists of constant values.
- `constant_values=0` specifies that the border values should be zero.



**Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.**

**Ans4.** To create an array of integers from 10 to 60 with a step of 5, you can use the `np.arange` function. Here's the code:

In [ ]:
import numpy as np

# Create an array from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)
print("Array from 10 to 60 with step 5:")
print(array)

### Explanation:
- `np.arange(start, stop, step)` generates values starting from `start` up to (but not including) `stop`, with a specified `step`.
- Here, it starts at 10, goes up to 60, and increments by 5.

Output:

In [ ]:
[10 15 20 25 30 35 40 45 50 55 60]

**Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.**

**Ans05.** You can perform string operations on a NumPy array of strings using `np.char` functions. Here’s how you can apply different case transformations:

### Code:

In [ ]:
import numpy as np

# Step 1: Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])
print("Original Array:")
print(array)

# Step 2: Apply case transformations
uppercase_array = np.char.upper(array)   # Convert to uppercase
lowercase_array = np.char.lower(array)   # Convert to lowercase
titlecase_array = np.char.title(array)   # Convert to title case (capitalize each word)

# Display results
print("\nUppercase Transformation:")
print(uppercase_array)

print("\nLowercase Transformation:")
print(lowercase_array)

print("\nTitle Case Transformation:")
print(titlecase_array)


### Explanation:
- `np.char.upper(array)`: Converts all characters in the array to uppercase.
- `np.char.lower(array)`: Converts all characters in the array to lowercase.
- `np.char.title(array)`: Capitalizes the first character of each word.

### Example Output:

In [ ]:
Original Array:
['python' 'numpy' 'pandas']

Uppercase Transformation:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Transformation:
['python' 'numpy' 'pandas']

Title Case Transformation:
['Python' 'Numpy' 'Pandas']

**Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.**

**Ans6.** You can insert a space between each character of every word in a NumPy array of strings using `np.char.join`. Here's how you can do it:

### Code:

In [ ]:
import numpy as np

# Step 1: Create a NumPy array of words
words = np.array(['python', 'numpy', 'array'])
print("Original Array:")
print(words)

# Step 2: Insert a space between each character
spaced_words = np.char.join(' ', words)
print("\nWords with Spaces Between Characters:")
print(spaced_words)

### Explanation:
- `np.char.join(' ', array)` joins the characters of each word in the array with a specified separator (`' '` in this case).
- This effectively inserts a space between every character of each word.

### Example Output:

In [ ]:
Original Array:
['python' 'numpy' 'array']

Words with Spaces Between Characters:
['p y t h o n' 'n u m p y' 'a r r a y']

**Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**

**Ans7.** Here's how you can create two 2D NumPy arrays and perform element-wise operations like addition, subtraction, multiplication, and division:

### Code:

In [ ]:
import numpy as np

# Step 1: Create two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

# Step 2: Perform element-wise operations
addition = array1 + array2  # or np.add(array1, array2)
subtraction = array1 - array2  # or np.subtract(array1, array2)
multiplication = array1 * array2  # or np.multiply(array1, array2)
division = array1 / array2  # or np.divide(array1, array2)

# Step 3: Display results
print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)

### Explanation:
1. **Addition** (`+` or `np.add`): Adds corresponding elements from `array1` and `array2`.
2. **Subtraction** (`-` or `np.subtract`): Subtracts corresponding elements of `array2` from `array1`.
3. **Multiplication** (`*` or `np.multiply`): Multiplies corresponding elements of the arrays.
4. **Division** (`/` or `np.divide`): Divides corresponding elements of `array1` by `array2`.

### Example Output:

In [ ]:
Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Element-wise Addition:
[[ 6  8]
 [10 12]]

Element-wise Subtraction:
[[-4 -4]
 [-4 -4]]

Element-wise Multiplication:
[[ 5 12]
 [21 32]]

Element-wise Division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

**Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.**

**Ans8.** Here's how you can create a 5x5 identity matrix and extract its diagonal elements using NumPy:

### Code:

In [ ]:
import numpy as np

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Step 2: Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)

### Explanation:
1. **`np.eye(5)`**:
   - Creates a 5x5 identity matrix (a square matrix with ones on the diagonal and zeros elsewhere).
2. **`np.diag(matrix)`**:
   - Extracts the diagonal elements of the matrix as a 1D array.

### Example Output:

In [ ]:
5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]

**Q9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.**

**Ans9.** To identify prime numbers in a NumPy array of random integers, we need a helper function to check for primality. Here's how you can implement it step by step:

### Code:

In [ ]:
import numpy as np

# Step 1: Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)
print("Random Array:")
print(random_array)

# Step 2: Define a helper function to check for primality
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

# Step 3: Use a vectorized approach to find all prime numbers in the array
prime_numbers = np.array([num for num in random_array if is_prime(num)])
print("\nPrime Numbers in the Array:")
print(prime_numbers)

### Explanation:
1. **`np.random.randint(0, 1001, size=100)`**:
   - Generates 100 random integers between 0 and 1000.
2. **Helper Function `is_prime(num)`**:
   - Checks if a number is prime by iterating from 2 to \(\sqrt{\text{num}}\) and checking divisibility.
3. **List Comprehension**:
   - Filters the array to include only the numbers for which `is_prime` returns `True`.

### Example Output:

In [ ]:
Random Array:
[145 381 203 ... 602 791 199]

Prime Numbers in the Array:
[199 281 599 613 661 ...]

**Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.**

**Ans10.** To calculate the weekly averages of daily temperatures for a month, we can:

1. Generate a NumPy array with daily temperatures for a month (assuming 30 days).
2. Reshape the array into a 4x7 matrix (representing 4 weeks and 7 days).
3. Calculate the weekly averages using `np.mean`.

Here’s how you can do it:

### Code:

In [ ]:
import numpy as np

# Step 1: Generate a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.uniform(low=15, high=35, size=30)  # Random temperatures between 15 and 35
print("Daily Temperatures for the Month:")
print(daily_temperatures)

# Step 2: Reshape the array into a 4x7 matrix (4 weeks, 7 days each)
weekly_temperatures = daily_temperatures.reshape(4, 7)
print("\nWeekly Temperatures (4x7 matrix):")
print(weekly_temperatures)

# Step 3: Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)
print("\nWeekly Average Temperatures:")
print(weekly_averages)

### Explanation:
1. **`np.random.uniform(low=15, high=35, size=30)`**:
   - Generates 30 random temperatures between 15°C and 35°C.
2. **`reshape(4, 7)`**:
   - Reshapes the 30 temperatures into a 4x7 matrix where each row represents a week.
3. **`np.mean(weekly_temperatures, axis=1)`**:
   - Calculates the mean for each week (along the rows of the matrix).

### Example Output:

In [ ]:
Daily Temperatures for the Month:
[20.34 22.14 18.56  ... 28.32 21.49 23.17]

Weekly Temperatures (4x7 matrix):
[[20.34 22.14 18.56  ...]
 [25.74 28.32 26.04 ...]
 [19.94 24.74 27.98 ...]
 [22.51 21.79 23.97 ...]]

Weekly Average Temperatures:
[22.56 25.39 24.16 23.49]



The weekly averages are calculated by averaging the values in each row of the reshaped matrix.

